In [21]:
import numpy as np

In [22]:
n = int(input("Enter the number of equations: ")) 
var = int(input("Enter the number of variables: "))

In [23]:
l = []
for i in range(n):
    row = []
    for j in range(var):
        val = float(input(f"Enter the coefficient of variable {j+1} in equation {i+1}: "))
        row.append(val)
    l.append(row)
mat = np.array(l)

In [24]:
print(mat)

[[0. 0. 2.]
 [1. 2. 3.]
 [2. 4. 6.]]


In [25]:
def RowOper_1(mat, r, c):
    mat[r,:] /= mat[r][c]

def RowOper_2(mat, r1, r2, c):
    mat[r2,:] -= mat[r2][c]*mat[r1,:]

def RowOper_3(mat, r1, r2):
    mat[[r1, r2]] = mat[[r2, r1]]

In [26]:
def GaussianElimination(mat, n, var):
    curr = 0
    for j in range(var):
        if curr < n:
            flag = 0
            for i in range(curr , n):
                if mat[i][j]!=0:
                    flag = 1
                    break
            if flag==0:
                continue
            else:
                RowOper_3(mat, curr, i)
                RowOper_1(mat, curr, j)
                for k in range(0, n):
                    if k != curr:
                        RowOper_2(mat, curr, k, j)
            curr+=1
        else:
            break

In [27]:
GaussianElimination(mat, n, var)

In [28]:
print(mat)

[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
