In [7]:
import numpy as np

In [20]:
n = 10

In [21]:
l = []
for i in range(n):
    row = []
    for j in range(n):
        if i == j:
            row.append(n*(i+1)+j+1)
        else:
            row.append(j+1)
    l.append(row)
l[0][0] = float(l[0][0])
mat = np.array(l)

In [22]:
print(mat)

[[ 11.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.  22.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.  33.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.  44.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.  55.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.  66.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.  77.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.  88.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.  99.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9. 110.]]


In [23]:
b = [n*(2*(i+1)+n+1)/2.0 for i in range(n)]
print(b)

[65.0, 75.0, 85.0, 95.0, 105.0, 115.0, 125.0, 135.0, 145.0, 155.0]


In [24]:
def RowOper_1(mat, r, c):
    mat[r,:] /= mat[r][c]

def RowOper_2(mat, r1, r2, c):
    mat[r2,:] -= mat[r2][c]*mat[r1,:]

def RowOper_3(mat, r1, r2):
    mat[[r1, r2]] = mat[[r2, r1]]

In [ ]:
def GaussianElimination(mat, n):
    curr = 0
    for j in range(n):
        if curr < n:
            flag = 0
            for i in range(curr , n):
                if mat[i][j]!=0:
                    flag = 1
                    break
            if flag==0:
                continue
            else:
                RowOper_3(mat, curr, i)
                b[curr] /= mat[curr][j]
                RowOper_1(mat, curr, j)
                for k in range(curr+1, n):
                    if k != curr:
                        b[k] -= b[curr] * mat[k][j]
                        RowOper_2(mat, curr, k, j)
            curr+=1
        else:
            break

In [26]:
GaussianElimination(mat, n)

In [27]:
print(mat)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [28]:
print(b)

[0.9999999999999998, 1.0000000000000004, 1.0000000000000002, 1.0000000000000004, 0.9999999999999999, 1.0, 1.0, 1.0, 0.9999999999999999, 1.0000000000000002]
