# LU Factorisation

Any non-singular matrix with leading minors non-singular can be uniquely expressed as the product of a lower and upper triangular matrix i.e A = LU   

## Algorithm   

Initialize L and U to 0   
then for i = 1, 2, ... , size(A) do:   
- set L[i][i] to 1
- set t = 0
- for j = 1, 2, 3, ... , i-1 do:
  - t += L[i][j] * U[j][i]
- U[i][i] = A[i][i] - t
- for j  = i+1, ... , size(A) do:
  - t = 0
  - for k = 1, 2, 3, ... , i-1 do:
    - t += L[j][k] * U[k][i]
  -  L[j][i] = (A[j][i] - t)/U[i][i]
- for j  = i+1, ... , size(A) do:
  - t = 0
  - for k = 1, 2, 3, ... , i-1 do:
    - t += L[i][k] * U[k][j]
  -  U[i][j] = A[i][j] - t

Now to solve an equation Ax = b, take Ux as y and solve Ly = b using forward substitution    
Then solve Ux = y using back substitution to get the final value of x

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1, 1], [4, 3, -1], [3, 5, 3]], dtype = np.float64)
M = A.copy()

In [3]:
b = np.array([1, 6, 4], dtype = np.float64)

In [4]:
# Initializing L and U
# A is non-singular so U will not have any diagonal entry as 0
L = np.zeros_like(A, dtype = np.float64)
U = np.zeros_like(A, dtype = np.float64)

In [5]:
def LU_fact():
    # Implementing the Algorithm above
    
    n = len(A)
    for i in range(n):
        L[i][i] = 1
        t = 0

        for j in range(i):
            t += L[i][j] * U[j][i]
        U[i][i] = A[i][i] - t

        for j in range(i+1, n):
            t = 0
            for k in range(i):
                t += L[j][k] * U[k][i]
            L[j][i] = (A[j][i] - t)/U[i][i]

        for j in range(i+1, n):
            t = 0
            for k in range(i):
                t += L[i][k] * U[k][j]
            U[i][j] = A[i][j] - t

In [6]:
LU_fact()      # Finding the LU factorisation of A
print(f"A is :\n{M}")
print(f"\nL is :\n{L}")
print(f"\nU is :\n{U}")

A is :
[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]

L is :
[[ 1.  0.  0.]
 [ 4.  1.  0.]
 [ 3. -2.  1.]]

U is :
[[  1.   1.   1.]
 [  0.  -1.  -5.]
 [  0.   0. -10.]]


In [7]:
print(f"Product of L and U is: \n{L@U}")     # Confirming that LU = A

Product of L and U is: 
[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]


In [8]:
# Taking Ux = y and solving Ly = b for y by forward substitution
def for_sub(L, b):
    n = len(L)
    x = [b[0] / L[0][0]] + [0]*(n-1)
    for i in range(1, n):
        s = 0
        for j in range(i):
            s += L[i][j] * x[j]
        x[i] = (b[i] - s) / L[i][i]
    return x

In [9]:
y = for_sub(L, b)

In [10]:
# Solving Ux = y for x by back substitution
def back_sub(U, b):
    n = len(U)
    x = [0]*(n-1) + [b[n-1] / U[n-1][n-1]]
    for i in range(n-2, -1, -1):
        s = 0
        for j in range(i+1, n):
            s += U[i][j] * x[j]
        x[i] = (b[i] - s) / U[i][i]
    return x

In [11]:
x = back_sub(U, y)

In [14]:
x1, x2, x3 = x
print(f"The final solution is:\nx1: {x1}\nx2: {x2}\nx3: {x3}")

The final solution is:
x1: 1.0
x2: 0.5
x3: -0.5
